/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class AddingPat extends javax.swing.JFrame {

    /**
     * Creates new form AddingPat
     */
    public AddingPat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        create = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patid = new javax.swing.JTextField();
        mid = new javax.swing.JTextField();
        first = new javax.swing.JTextField();
        lst = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        bd = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        att = new javax.swing.JTextField();
        emer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        diag = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        create.setBackground(new java.awt.Color(0, 204, 204));
        create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        create.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 0, 21, 31));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("PATIENT ID:");
        create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 83, 39));
        create.add(patid, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 105, 225, 33));

        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        create.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 216, 225, 33));
        create.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 161, 225, 33));

        lst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstActionPerformed(evt);
            }
        });
        create.add(lst, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 267, 225, 33));
        create.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 105, 181, 33));
        create.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 318, 225, 33));
        create.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 159, 181, 36));
        create.add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 216, 181, 33));
        create.add(emer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 181, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("FIRST NAME:");
        create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("MIDDLE NAME:");
        create.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("LAST NAME:");
        create.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("BIRTHDATE:");
        create.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("AGE:");
        create.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 114, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("GENDER:");
        create.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("ATTENDING PHYSICIAN:");
        create.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 225, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("DIAGNOSIS:");
        create.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        add.setBackground(new java.awt.Color(153, 255, 204));
        add.setText("ADD");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        create.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 106, 34));

        del.setBackground(new java.awt.Color(153, 255, 204));
        del.setText("DELETE");
        del.setBorder(null);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        create.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 106, 34));

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setText("BROWSE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        create.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 201, 69, 23));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE PATIENT'S INFORMATIONS");
        create.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 255, 204));
        jLabel12.setForeground(new java.awt.Color(51, 255, 204));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        create.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 99, 102, 96));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("x");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(878, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        create.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 916, 50));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("EMERGENCY CONTACT:");
        create.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 276, -1, -1));
        create.add(diag, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 181, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconpics/agrs (1).jpg"))); // NOI18N
        create.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, 410));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconpics/abin.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        create.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 460, 400));

        jPanel1.add(create);
        create.setBounds(0, 0, 920, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.dispose();
        Manage ap = new Manage();
        ap.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnaf = new FileNameExtensionFilter("IMAGES", "png","jpg","jpeg");
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION);
        File selectedImageFile = browseImageFile.getSelectedFile();
        String selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null,selectedImagePath);

        ImageIcon ii = new ImageIcon(selectedImagePath);

        Image image = ii.getImage().getScaledInstance(jLabel12.getWidth(),jLabel12.getHeight(), Image.SCALE_SMOOTH);
        jLabel12.setIcon(new ImageIcon (image));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        patid.setText(null);
        first.setText(null);
        mid.setText(null);
        lst.setText(null);
        bd.setText(null);
        age.setText(null);
        gen.setText(null);
        att.setText(null);
        emer.setText(null);
       diag.setText(null);
        
    }//GEN-LAST:event_delActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Manage.AddRowToJTable(new Object[]{
            patid.getText(),
            first.getText(),
            mid.getText(),
            lst.getText(),
            bd.getText(),
            age.getText(),
            gen.getText(),
            att.getText(),
            emer.getText(),
            diag.getText(),
           

        });
    }//GEN-LAST:event_addActionPerformed

    private void lstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
    
       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingPat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField age;
    private javax.swing.JTextField att;
    private javax.swing.JTextField bd;
    private javax.swing.JPanel create;
    private javax.swing.JButton del;
    private javax.swing.JTextField diag;
    private javax.swing.JTextField emer;
    private javax.swing.JTextField first;
    private javax.swing.JTextField gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lst;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField patid;
    // End of variables declaration//GEN-END:variables
}
