/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class Manage extends javax.swing.JFrame {

    /**
     * Creates new form Manage
     */
    public Manage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelist = new javax.swing.JTable();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        search1 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 383));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATIENT'S LIST OF RECORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 780, 50);

        tablelist.setAutoCreateRowSorter(true);
        tablelist.setBackground(new java.awt.Color(153, 255, 204));
        tablelist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aeron Villafuerte", "Argao,Cebu", "09323987715", "Female", "20", "093457621", "Dr.Krztel Camello", "10/11/12", "buang"},
                {"Sweet Casia", "Minglanilla", "095643278", "Female", "19", "075643289", "Dr.Kryztel Camello", "09/11/23", "mini"},
                {"Darla Ipon", "Minglanilla", "097654328", "Female", "21", "098765432", "Dr.Kryztel Camello", "02/03/23", "shano"},
                {"Caryll Deiparine", "Sibonga", "098765432", "Female", "19", "012346758", "Dr.Kryztel Camello", "09/23/23", "kigwa"},
                {"Edgardo Siton", "Mingalnilla", "09876123", "Male", "50", "09814354657567", "Dr. Kryztel Camello", "07/01/23", "animal"}
            },
            new String [] {
                "Name", "Address", "Phone Number", "Gender", "Age", "Emergency Contant", "Att. Physician", "Date (Visited)", "Diagnosis"
            }
        ));
        tablelist.setGridColor(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(tablelist);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 770, 280);

        add.setBackground(new java.awt.Color(102, 255, 204));
        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setText("ADD");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(20, 80, 80, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(770, 10, 11, 22);

        delete.setBackground(new java.awt.Color(102, 255, 204));
        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(110, 80, 80, 23);

        search1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        search1.setOpaque(false);
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1);
        search1.setBounds(340, 80, 350, 30);

        search.setBackground(new java.awt.Color(102, 255, 204));
        search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(700, 80, 80, 30);

        update.setBackground(new java.awt.Color(102, 255, 204));
        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(200, 80, 80, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 60, 770, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(794, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        AddingPat ap= new AddingPat();
        ap.setVisible(true);
        ap.pack();
        ap.setLocationRelativeTo(null);
        ap.setDefaultCloseOperation(Manage.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel)tablelist.getModel();
        try{
            int SelectedRowIndex = tablelist.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)tablelist.getModel();
        TableRowSorter< DefaultTableModel> obj = new TableRowSorter<>(model);
        tablelist.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search1.getText()));
    }//GEN-LAST:event_search1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      DefaultTableModel model = (DefaultTableModel)tablelist.getModel();
        TableRowSorter< DefaultTableModel> obj = new TableRowSorter<>(model);
        tablelist.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search1.getText()));
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)tablelist.getModel();
         int selectedRowIndex = tablelist.getSelectedRow();
         
        String name = model.getValueAt(selectedRowIndex,0).toString();
        String address = model.getValueAt(selectedRowIndex,1).toString();
        String phone = model.getValueAt(selectedRowIndex,2).toString();
        String gender = model.getValueAt(selectedRowIndex,3).toString();
        String age= model.getValueAt(selectedRowIndex,4).toString();
        String emer = model.getValueAt(selectedRowIndex,5).toString();
        String att = model.getValueAt(selectedRowIndex,6).toString();
        String date= model.getValueAt(selectedRowIndex,7).toString();
        String diag= model.getValueAt(selectedRowIndex,8).toString();
        
        String NewName= JOptionPane.showInputDialog(null,"Enter the new name:",name);
        String NewAddress= JOptionPane.showInputDialog(null,"Enter the new address:",address);
        String NewPhone= JOptionPane.showInputDialog(null,"Enter the new phone number:",phone);
        String NewGender= JOptionPane.showInputDialog(null,"Enter the new gender:",gender);
        String NewAge= JOptionPane.showInputDialog(null,"Enter the new age:",age);
        String NewEmer= JOptionPane.showInputDialog(null,"Enter the new emergency contact:",emer);
        String NewAtt= JOptionPane.showInputDialog(null,"Enter the new attending physician:",att);
        String NewDate= JOptionPane.showInputDialog(null,"Enter the new date:",date);
        String NewDiag= JOptionPane.showInputDialog(null,"Enter the new diagnosis:",diag);
        
        model.setValueAt(NewName, selectedRowIndex,0);
        model.setValueAt(NewAddress, selectedRowIndex, 1);
        model.setValueAt(NewPhone, selectedRowIndex, 2);
        model.setValueAt(NewGender, selectedRowIndex, 3);
        model.setValueAt(NewAge, selectedRowIndex, 4);
        model.setValueAt(NewEmer, selectedRowIndex, 5);
        model.setValueAt(NewAtt, selectedRowIndex, 6);
        model.setValueAt(NewDate, selectedRowIndex, 7);
        model.setValueAt(NewDiag, selectedRowIndex, 8);
        
        
        
    }//GEN-LAST:event_updateActionPerformed
 public static void AddRowToJTable(Object[] dataRow)
    {
       DefaultTableModel model = (DefaultTableModel)tablelist.getModel();
       model.addRow(dataRow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton search;
    private javax.swing.JTextField search1;
    private static javax.swing.JTable tablelist;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
